### ISSUE TITLE
about crypto-algorithms view

### ISSUE THREAD

**Issue by chanrai** [blackducksoftware/blackduck-common-api#15]
I can get the follow url about encryption from API.

{"rel":"crypto-algorithms","href":"https://****/api/components/8cbff3a8-1079-481b-b65c-02d83139bbe2/versions/41203927-1ffe-442e-9315-04f02babc9da/crypto-algorithms"}]}}

but I can't found View Class about encryption just like Class VulnerabilityWithRemediationView, Is there view provided by encryption?
thanks.

**Comment by ekerwin** [comment]
No, we haven't had a need yet for this class so it doesn't exist.
